language: python
python: '3.7'
cache:
- pip
- npm
dist: xenial
matrix:
  include:
  - stage: install
    before_install:
    - nvm install 8
    - openssl aes-256-cbc -k $SS_PW -in gae-keyfile-dev.json.enc -out gae-keyfile-dev.json
      -d
    install:
    - pip install -r requirements.txt
    - cd frontend
    - npm install
    script: skip
  - stage: test
    script:
    - flake8 .
    - mypy invisible_flow
    - pytest --cov=invisible_flow tests
    - python run-api-tests.py
    - cd frontend
    - npm install && npm run test
  - stage: Heroku_deploy
    deploy:
      provider: heroku
      api_key:
        secure: Sw81Cd2HcEhMm6lKhyxw5twVo6GR5cNFZu+yvu+8/bqVAUwFPvEiiPOxYYt4aKkMqu9aWY7YhQLn6nvVf0mTDjX9sQE9SCmSHfw3YhPWRExX97G05j8HFY/L9D20RyCHGfHoceC5N4JPoxZGTGKBiONhAqC8a5nlCWgujjiNIWUXEQmLIMKwhxugJ+3IPbPIDdvrwpBnPF14y9rPoFnwnClxI7sVfuzqwgC3uKuvr8difB0X4nEt10D0d6glrWEZXF3uQOoI04bh9HDSkoIiKG3r5IP3sOyTTkOxlPnkRcmt6OB+Qic15xnWigmO7JTYGTkhhKLzVWEO8QFvrPF6DAyfXn7nshOaGZOCkmmuxSh0ppgAu0miZQ2Zmp02pBSiPq5MTnBKw5KyXg1Huh0N4Nnf0Tbk4mlv11RWfpzhJa9cC5LYmJGJkOnO+YUNk1v0dusht5ai+gfVLEvk9x8eM8lEJgKZwrfVijeGgBm1smkCFkOSEOGWU9TRZ/g3JePUTEg+mAxA88whEaUTPZPTPOXEfOmEXKa794pBD+N/vFNeMbfPGS6fJE8XTBuTRbptWZ5nuwqgIOVa5tpc9ml2cxQYUl3EpbBbFBBzNG8BApsFqR9kJVUeZzuAH6cQI8+rPzzhpdffG45vI3S/ZAowEKqpKt2Q0Aj7MO9sKD6TukI=
      strategy: git
      app: invisiflow-staging
      on:
        repo: invinst/invisible-flow
        all_branches: true
    script: skip
  - stage: GCS_deploy
    if: branch = master
    before_script:
    - echo "${TRAVIS_COMMIT}" > invisible_flow/commit
    - cd frontend
    - npm install && npm run build
    deploy:
    - provider: gae
      keyfile: "$GAE_KEYFILE"
      project: "$GAE_PROJECT_ID"
      version: "$GAE_VERSION"
      file:
      - invisible_flow/commit
      on:
        repo: invinst/invisible-flow
      skip_cleanup: true
    - provider: gcs
      edge:
        branch: gcs-ng
      project_id: "$GAE_PROJECT_ID"
      credentials: "../gae-keyfile-dev.json"
      bucket: invisible-flow-dev
      local-dir: frontend/build
      on:
        repo: invinst/invisible-flow
      skip_cleanup: true
      acl: public-read
    env:
    - GIT_COMMIT_ID=`echo $TRAVIS_COMMIT`
    - PUBLIC_URL=https://storage.cloud.google.com/invisible-flow-dev/
    after_script:
    - cat invisible_flow/commit
    script: skip
env:
  global:
    secure: QtSkwjcslKJ7LyjP0cLuiIBbL6P+aii0xN+2sk2YS3IK4jDVyagyPcDmXAGml7uqXZjgSj6TBoJP8t51S9OJSG4HZhfcG5cj62q/RiglONSQzqHKOCaBfEypd8Nrtkx31MMQLmpJuIHrZtQUhHN1vBYDzdo0Iti/5CukgSqb67RuxL1aGmXkUkAJwd8JTmgH85dfZ+E5sD4Ns3LU3F5IQqk7gJ/y9gLMmV8wiUWStBwTeQCV8Kp9qVMFUonHAB5OzEuYRaasYr05XlcyByxWOJPhcPHEkXs1KGobhjph07UxZ49ORzrvtj6Go0hDLkti5Nenpltc1w4nrXg7AsNC4eACZ0WzSTmqXJ5g9UPzUgElxj1bnfqQSokL9Fxq/rZc3nObbnfdimSRXqbs8MOXPlyLM3CEU3kpkm6zAybZEXGBqAE763EJy9FNVptz4rdU0PDpwuCwi1e2QwXZhu8xc/Y93p5fT5QJqT4RL0hhv5S54XmSXH9YPx+7vxZcRbCeOi0UVg0CDer1gtImGZCiPwer8BvqP8RCcSYzQIJ4mhI764HpIOnFI4kgn9VAxnIe6HZCTZM88vc9znmk4Am/+HEnivhDoSOW6XFnvcUz3N81pX28zdIG9l8EsMvV7Ls+cVeNhiRcRCovI2XQqiwlS9tj8IxiuEt9sJXuSE/c3K0=

