language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - conda update --yes conda
  - conda env create -f environment.yml
  - conda activate invisible-flow-env
script:
  - flake8 .
  - pytest --cov=invisible_flow tests