os: linux
dist: xenial
language: python
python: '3.7'
cache:
  - directories:
    - $HOME/.npm
  - pip
jobs:
  include:
  - stage: install
    install:
    - pip install -r requirements.txt
    - cd frontend
    - npm ci
    script: skip
  - stage: test
    script:
    - flake8 .
    - mypy invisible_flow
    - pytest --cov=invisible_flow tests
    - python run-api-tests.py
    - cd frontend
    - npm ci && npm run test
  - stage: Heroku_deploy
    before_deploy: cd frontend && npm ci && npm run build
    deploy:
      provider: heroku
      api_key:
        secure: GsyQtlDMGVfKTtwBlYYGUmgeP6Mic5lqGV1i/MkITRgbLyjp/tCF/VeH3ueoFMdgZ6mm8b8O4l2A1Zn1+J4HTtHtX/NEaxP6vYxghqbC2vMpSMYfiQ1zsk3qlLz/f4PtvRURpjXFVP5XHUGn8EbqnGDq3QQTFNKib8UpJaoTKzwVsrhFdc8/HoIvkllq2zwTlUXx/pGs+kxsg8JdWJA5J7pADASyx3e0yo3uUtXMs0oXHl9l85cdMCCwr2pSEsYcaqttsJ7+ax3yUzQoE7Es5Kk6NcA8UBCw0+NVYF1iugZ8850bRUacG/UmvrPZDgs8AQcov26tytck1n497wMj7xIICGkXrsNF1J38gwtoc2CL8xFpzhzn/qPUt+HrNKPaW4/7oJRY8dahlpUBdpkqeUhBHFASkaSj0klOvbTLgnsL6euhesjfloIu0MJ0iWZy/AeD3C0+mJmOq41Pi8ArPT19Acna4pV5rWUpwojS2MKviBI3/q1EDxnITXKzJ2xE6CIDEX2dZOJ7JAhjMvRVUp/kYrWbSbT7sMW/ARX7GEOr4tkhI2hVguibEKdnKB1d6QHhQ1JMsEWzR3gKOhJ6lHOPpqdiT1s6xlqZnOZ+ytSNEuESGRrOZYi68tUSdH+xzoQ1x8vG23AFpgM3TRZqNelrihnrXIFiGY6yK2gtc48=
      app: invisiflow-testing
      on:
        repo: invinst/invisible-flow
      skip_cleanup: true
    script: skip
  - stage: GCS_deploy
    if: branch = master
    before_script:
    - openssl aes-256-cbc -k $SS_PW -in gae-keyfile-dev.json.enc -out gae-keyfile-dev.json -d
    - echo "${TRAVIS_COMMIT}" > invisible_flow/commit
    - cd frontend
    - npm ci && npm run build
    deploy:
    - provider: gae
      keyfile: "$GAE_KEYFILE"
      project: "$GAE_PROJECT_ID"
      version: "$GAE_VERSION"
      file:
      - invisible_flow/commit
      on:
        repo: invinst/invisible-flow
      skip_cleanup: true
    - provider: gcs
      edge:
        branch: gcs-ng
      project_id: "$GAE_PROJECT_ID"
      credentials: "../gae-keyfile-dev.json"
      bucket: invisible-flow-dev
      local-dir: frontend/build
      on:
        repo: invinst/invisible-flow
      skip_cleanup: true
      acl: public-read
    env:
    - GIT_COMMIT_ID=`echo $TRAVIS_COMMIT`
    - PUBLIC_URL=https://storage.cloud.google.com/invisible-flow-dev/
    after_script:
    - cat invisible_flow/commit
    script: skip
env:
  global:
    secure: QtSkwjcslKJ7LyjP0cLuiIBbL6P+aii0xN+2sk2YS3IK4jDVyagyPcDmXAGml7uqXZjgSj6TBoJP8t51S9OJSG4HZhfcG5cj62q/RiglONSQzqHKOCaBfEypd8Nrtkx31MMQLmpJuIHrZtQUhHN1vBYDzdo0Iti/5CukgSqb67RuxL1aGmXkUkAJwd8JTmgH85dfZ+E5sD4Ns3LU3F5IQqk7gJ/y9gLMmV8wiUWStBwTeQCV8Kp9qVMFUonHAB5OzEuYRaasYr05XlcyByxWOJPhcPHEkXs1KGobhjph07UxZ49ORzrvtj6Go0hDLkti5Nenpltc1w4nrXg7AsNC4eACZ0WzSTmqXJ5g9UPzUgElxj1bnfqQSokL9Fxq/rZc3nObbnfdimSRXqbs8MOXPlyLM3CEU3kpkm6zAybZEXGBqAE763EJy9FNVptz4rdU0PDpwuCwi1e2QwXZhu8xc/Y93p5fT5QJqT4RL0hhv5S54XmSXH9YPx+7vxZcRbCeOi0UVg0CDer1gtImGZCiPwer8BvqP8RCcSYzQIJ4mhI764HpIOnFI4kgn9VAxnIe6HZCTZM88vc9znmk4Am/+HEnivhDoSOW6XFnvcUz3N81pX28zdIG9l8EsMvV7Ls+cVeNhiRcRCovI2XQqiwlS9tj8IxiuEt9sJXuSE/c3K0=
