os: linux
dist: xenial
language: python
python: '3.7'
cache:
- directories:
  - "$HOME/.npm"
- pip
services:
- postgresql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
jobs:
  include:
  - stage: test
    install:
    - pip install -r requirements.txt
    - cd frontend
    - npm ci && cd ..
    before_script:
    - psql -c "create user invisible_flow;"
    - psql -c "create database invisible_flow_testing with owner invisible_flow;"
    - psql invisible_flow_testing -c "CREATE EXTENSION postgis;"
    - export ENVIRONMENT=travis
    script:
    - flake8 .
    - mypy invisible_flow
    - pytest --cov=invisible_flow tests --cov-fail-under 70
    - python run-api-tests.py
    - cd frontend
    - npm run test && cd ..
  - stage: Heroku_deploy
    if: branch = master
    before_deploy: cd frontend && npm ci && npm run build && cd ..
    deploy:
      provider: heroku
      api_key:
        secure: a50B/74xoHB4TJJTOMPyJ88o7dX235ioRRxYqYTv0aVwmuqiwq2rB6TIuF+SmXGR++JG/mW2Ej9p4zp8jXAQ2KB52cOl3rcX1AGzwgBqnOM6NLj2DNdupBaTJU7jrL8ldVQ/NMKf29UX4+/oZZEACazg/yWCvfHQCjZ4NW2u3vl53a0v2q07YtsI1JLRq9MsuA2WvHFMB6CxHQSWhgDB+yzmFmzAeBjrKegmsYWoM3RtOyMiaL6THmaQsKVZUxtBebLYyuGIfno5LlPSxh5q6+9d0EvBufsC4bY9G2hM8rQBJOZsH6bsdbdOXF3pnhVjPI1lZ3GbcoVOAv+qmIZB58+J/uWvq3xq7eVEHzZbkpu07Eg1QWlPlFqpzccI+pxcjoilWdtcZRn3u8lU0aH+3gQDTV/NeWyXFbSMTYlY7yem/E35uEqooyt48Y3c+7QgrLl8s9rUUjcLzAOcalFVEbHppK2vHfJ7q/f8GbxNLu/f3OaAzPsiToRWXAH5Qx1neABkcK3HnEUnjJ+LzKY9LHxOGvXDBug1IP4SwLsVS+YGFQ2ST52TC3guDzxiMf/lU/TLyJtrROjdut0za8cKlKPKIRay/Grbkjo+lEj/ix4QGU6feZNh83Pw7kYQ4XGHgdjeY35BFpn9nkDnjR44pnxpHx1kr3J3VpOF2PbvlUw=
      app: invisiflow-testing
      on:
        repo: invinst/invisible-flow
      skip_cleanup: true
    script: skip
env:
  global:
    secure: QtSkwjcslKJ7LyjP0cLuiIBbL6P+aii0xN+2sk2YS3IK4jDVyagyPcDmXAGml7uqXZjgSj6TBoJP8t51S9OJSG4HZhfcG5cj62q/RiglONSQzqHKOCaBfEypd8Nrtkx31MMQLmpJuIHrZtQUhHN1vBYDzdo0Iti/5CukgSqb67RuxL1aGmXkUkAJwd8JTmgH85dfZ+E5sD4Ns3LU3F5IQqk7gJ/y9gLMmV8wiUWStBwTeQCV8Kp9qVMFUonHAB5OzEuYRaasYr05XlcyByxWOJPhcPHEkXs1KGobhjph07UxZ49ORzrvtj6Go0hDLkti5Nenpltc1w4nrXg7AsNC4eACZ0WzSTmqXJ5g9UPzUgElxj1bnfqQSokL9Fxq/rZc3nObbnfdimSRXqbs8MOXPlyLM3CEU3kpkm6zAybZEXGBqAE763EJy9FNVptz4rdU0PDpwuCwi1e2QwXZhu8xc/Y93p5fT5QJqT4RL0hhv5S54XmSXH9YPx+7vxZcRbCeOi0UVg0CDer1gtImGZCiPwer8BvqP8RCcSYzQIJ4mhI764HpIOnFI4kgn9VAxnIe6HZCTZM88vc9znmk4Am/+HEnivhDoSOW6XFnvcUz3N81pX28zdIG9l8EsMvV7Ls+cVeNhiRcRCovI2XQqiwlS9tj8IxiuEt9sJXuSE/c3K0=
