os: linux
dist: xenial
language: python
python: '3.7'
cache:
- directories:
  - "$HOME/.npm"
- pip
services:
- postgresql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
jobs:
  include:
  - stage: test
    install:
    - pip install -r requirements.txt
    - cd frontend
    - npm ci && cd ..
    before_script:
    - psql -c "create user invisible_flow;"
    - psql -c "create database invisible_flow_testing with owner invisible_flow;"
    - psql invisible_flow_testing -c "CREATE EXTENSION postgis;"
    - export ENVIRONMENT=travis
    script:
    - flake8 .
    - mypy invisible_flow
    - pytest --cov=invisible_flow tests --cov-fail-under 70
    - python run-api-tests.py
    - cd frontend
    - npm run test && cd ..
  - stage: Heroku_deploy
    if: branch = master
    before_deploy: cd frontend && npm ci && npm run build && cd ..
    deploy:
      provider: heroku
      api_key:
        secure: LsoPKhseA4E6w44LK1YXsrBra7Pmbq2wI66H6q6zRm6nQwTB1YjMvseSGehNtI49tVRGsuOhLCjJjlzoA25j/BUzNqiv+FzvCFXog6nlJlmujE7I0mp7psFVyJerqPpDFAxBrUjVi1VWGjBsoYNNk+FwV83gqdnwp5ASTvx7FlYDHUErqQVHsdqS4OfA/eeuThFEzSO27X/O4p+M4O3BJ3zdj7towkAM7KO8Fcz/AgrvS0WTutPilE+ooO+3r8utqJflbGne/WzuJbuQd/9dmQ9hYcighJ/jLX3KJidOyIkeAhltQMvWD155DnSYkPWrHSKOwzuZcfzgQScWITzBWPeL5Q7N5BYqP7G9RD1fD4XVHtxgM/wEqJrm1XE0tcoEamv4lS96NVudI2UlyVE/9MPT/M9sQaom/fvd+Xx8ap0bMoMr8qnurGeYppRaDrnrfQmgLJfE5xiM6IZkW597M+G9eO6JxWSlAj4EKTVzWNqitV6wbieBmb6SGewweTvQIAPVtNZD/MQxcjr2BF3rJbe6HoJWZl3Ty5d/j3qkOMMGDZ/7iay4AAdyIDgvu84mtk+cr4Il6ntZzw/merV0vMjmeInVXg7Axtxp3aWG1FpRCjiV5e2hRlqxkLRag2HttCfCcwz2P7CwkUeGazJfEABiaXFI2o05g11pT060nWo=
      app: invisiflow-testing
      on:
        repo: invinst/invisible-flow
      skip_cleanup: true
    script: skip
env:
  global:
    secure: QtSkwjcslKJ7LyjP0cLuiIBbL6P+aii0xN+2sk2YS3IK4jDVyagyPcDmXAGml7uqXZjgSj6TBoJP8t51S9OJSG4HZhfcG5cj62q/RiglONSQzqHKOCaBfEypd8Nrtkx31MMQLmpJuIHrZtQUhHN1vBYDzdo0Iti/5CukgSqb67RuxL1aGmXkUkAJwd8JTmgH85dfZ+E5sD4Ns3LU3F5IQqk7gJ/y9gLMmV8wiUWStBwTeQCV8Kp9qVMFUonHAB5OzEuYRaasYr05XlcyByxWOJPhcPHEkXs1KGobhjph07UxZ49ORzrvtj6Go0hDLkti5Nenpltc1w4nrXg7AsNC4eACZ0WzSTmqXJ5g9UPzUgElxj1bnfqQSokL9Fxq/rZc3nObbnfdimSRXqbs8MOXPlyLM3CEU3kpkm6zAybZEXGBqAE763EJy9FNVptz4rdU0PDpwuCwi1e2QwXZhu8xc/Y93p5fT5QJqT4RL0hhv5S54XmSXH9YPx+7vxZcRbCeOi0UVg0CDer1gtImGZCiPwer8BvqP8RCcSYzQIJ4mhI764HpIOnFI4kgn9VAxnIe6HZCTZM88vc9znmk4Am/+HEnivhDoSOW6XFnvcUz3N81pX28zdIG9l8EsMvV7Ls+cVeNhiRcRCovI2XQqiwlS9tj8IxiuEt9sJXuSE/c3K0=
