os: linux
dist: xenial
language: python
python: '3.7'
cache:
- directories:
  - "$HOME/.npm"
- pip
services:
- postgresql
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
jobs:
  include:
  - stage: test
    install:
    - pip install -r requirements.txt
    - cd frontend
    - npm ci && cd ..
    before_script:
    - psql -c "create user invisible_flow;"
    - psql -c "create database invisible_flow_testing with owner invisible_flow;"
    - psql invisible_flow_testing -c "CREATE EXTENSION postgis;"
    - export ENVIRONMENT=travis
    script:
    - flake8 .
    - mypy invisible_flow
    - pytest --cov=invisible_flow tests --cov-fail-under 70
    - python run-api-tests.py
    - cd frontend
    - npm run test && cd ..
  - stage: Heroku_deploy
    if: branch = master
    before_deploy: cd frontend && npm ci && npm run build && cd ..
    deploy:
      provider: heroku
      api_key:
        secure: P8vg7namG/12t/NjiHERN/MB4XSjZRkiLlq0BBKl1JAZQgs9grhc9KSpAw6mGikZmqhsZo/borPft+Lufe22IUoL0i8IK+AKCwCYcvra4av0MTQohKkfQj+ndumUhoy2Skk0TgkjG7r9gwa9tzMhRzkjSCo6tNNiBYMSgKFPy1B0RJ0uhdi+UUGCPDEkb9CqGgFe767FSUNEVpU5UDSlXn3K5yFVBA+VkBok8Uu8Y8VQBpU4sIF14smbCZUBXp9eDXA0cpfcTOOEwunbzVIOLg9pOV7WL1utXe4/hyv0GdHrSGjn4anWiePXJlydjhhtJ9HmLptrpq4MyE/B4qBjOgZ/CUSjZm0MqsjzdwQH4zh4x9hA9K/y7ryvlsrZJCp2FyS/X1vbIUYPMQviHMUT2/V+lvlVHL70Hql4yN6Elp9I7ke9u/+Z+nCcwZtSJvtpElOtQn65XYhWO0hDB6h8aAtrpHlXv/tcTenO9JCp9bQOKhTS0qAXhEQbURZ/R0ohrGeq1LXVVM19EZEZgZO7UgNhqDCdJ6qWA+8z6hLlnZDzVCft7RK/C9of9q5CVCxJr4u/+ro4SKm7rspoB7Fs0S6rHUagltmDVcb53SkVMbLzOYc9FuK7PQUpnW+qvdAZwnDl0jYsl6fO+nl6duAMr2dn2oeVWKrWTvzmT5vEfAg=
      app: invisiflow-testing
      on:
        repo: invinst/invisible-flow
      skip_cleanup: true
    script: skip
env:
  global:
    secure: QtSkwjcslKJ7LyjP0cLuiIBbL6P+aii0xN+2sk2YS3IK4jDVyagyPcDmXAGml7uqXZjgSj6TBoJP8t51S9OJSG4HZhfcG5cj62q/RiglONSQzqHKOCaBfEypd8Nrtkx31MMQLmpJuIHrZtQUhHN1vBYDzdo0Iti/5CukgSqb67RuxL1aGmXkUkAJwd8JTmgH85dfZ+E5sD4Ns3LU3F5IQqk7gJ/y9gLMmV8wiUWStBwTeQCV8Kp9qVMFUonHAB5OzEuYRaasYr05XlcyByxWOJPhcPHEkXs1KGobhjph07UxZ49ORzrvtj6Go0hDLkti5Nenpltc1w4nrXg7AsNC4eACZ0WzSTmqXJ5g9UPzUgElxj1bnfqQSokL9Fxq/rZc3nObbnfdimSRXqbs8MOXPlyLM3CEU3kpkm6zAybZEXGBqAE763EJy9FNVptz4rdU0PDpwuCwi1e2QwXZhu8xc/Y93p5fT5QJqT4RL0hhv5S54XmSXH9YPx+7vxZcRbCeOi0UVg0CDer1gtImGZCiPwer8BvqP8RCcSYzQIJ4mhI764HpIOnFI4kgn9VAxnIe6HZCTZM88vc9znmk4Am/+HEnivhDoSOW6XFnvcUz3N81pX28zdIG9l8EsMvV7Ls+cVeNhiRcRCovI2XQqiwlS9tj8IxiuEt9sJXuSE/c3K0=
