entrypoint: gunicorn -b :$PORT invisible_flow.app:app -c gunicorn.config.py
runtime: python37
instance_class: F2
env_variables:
  GCS_BUCKET: 'twitterbot-180604.appspot.com'
  ENVIRONMENT: 'gae'

handlers:
- url: /.*
  script: auto